SUPPORTS_NATIVE_GOOGLE_CAMERA := NO

SUPPORTS_GOOGLE_WALLS := NO

SUPPORTS_GOOGLE_NEW_ASSISTANT := YES

SUPPORTS_GOOGLE_ASSISTANT_EXTRA_RESOURCES := YES

SUPPORTS_PIXEL_SETUP_OVERLAY := YES

PIXEL_SETUP_OVERLAY_TYPE := PIXELONE

TARGET_INCLUDE_OWN_CAMERA := NO

SUPPORTS_FACE_UNLOCK := YES
